### ISSUE TITLE
Mutable fields should not be "public static"

### ISSUE THREAD

**Issue by BhartiChh** [vaibhav962/jmonkeyengineFall2024#3]
*Describing the technical debt*
The appToApplet field in the AppletHarness class is currently marked as public static. This creates a risk of external modification to the field, which is a mutable HashMap. To prevent unauthorized or unintended changes, it should be made protected to restrict visibility and access.

*To Reproduce*
1. Open the AppletHarness.java file in the codebase.
2. Scroll to line 25 where the public static modifier is applied to appToApplet.
3. Notice that the field is mutable and publicly accessible.

Location: 
File: AppletHarness.java
Path: src/main/java.com/jme3/app/AppletHarness.java

Screenshot:
![bharti_before](https://github.com/user-attachments/assets/25cb4dc9-4a31-4978-8777-fc3fba8b1033)

*Expected behavior*
The field should be changed from public static to protected static to prevent direct access from outside the class.

Original:
public static final HashMap<LegacyApplication, Applet> appToApplet = new HashMap<LegacyApplication, Applet>();

Resolution:
protected static final HashMap<LegacyApplication, Applet> appToApplet  = new HashMap<LegacyApplication, Applet>();

*Additional context*
This change helps improve encapsulation and protects against potential issues stemming from external modifications to the appToApplet field.

**Comment by 0matleb2** [comment]
While it makes sense for traceability reasons to create our issues on the prof's repo, the instructions were to create them in our group repos.
